### ISSUE TITLE
Don't use non-standard evaluation

### ISSUE THREAD

**Issue by hadley** [trinker/pacman#61]
I think this is a huge design error with `library()` and `require()`. It adds a lot of extra complication to the code, makes it hard to program with, and only saves two key presses.

**Comment by Dasonk** [comment]
I agree with you in theory.  But at the same time that ship has sailed already.  A lot of people are used to being to do something like `library(pacman)` instead of `library("pacman")` so to make it nicer for them allowing `p_load(ggplot2)` seems like a natural thing to do for a package that is meant to make package management less of a hassle.

I guess we could be idealists and force people to use `p_load("ggplot2")` but we already have it coded to work either way.  It probably would reduce the amount of bugs I'm sure will get reported if we were strict in forcing character input instead.

Maybe we can get R to change the way `library` / `require` work around the same time we get CRAN to have better version management :D

I'll wait to see what Tyler has to chip in on this.

**Comment by trinker** [comment]
@Dasonk We were hoping for feedback from folks.  I thought we had tried to address the use of non-standard evaluation that can leave you in a pickle by providing escape hatches with `character.only` and `char` arguments to most of the more important functions.

With design for programming I can see @hadley's point.  In considering the design we tried to keep with expectations people may have had with `library` but also we do like saving 2 characters.  The 2 chars on one of the most frequently used functions in R (`library`) can add up over time in interactive use.  This (`library`'s frequent use) is likely why `library` uses non-standard evaluation.

That being said the code is heavier because of it.  That bothers me less than bug pronedness of non-standard evaluation for use in programming applications with **pacman** functions.  We foresaw people using **pacman** more interactively than for programming hence our design choices.  I'm willing to have heavier weight code that performs a task more intuitively (particularly here where speed performance isn't a terrible concern).  We're not wiling to have intuitive functions that will cause headaches because of buggy programming use though.  

I'd say this raises some questions in this discussion:

1. Does our escape hatches (`character.only` & `char`) still likely leave room for bugs?    
2. What would a better design look like?  (e.g., **dpyr** provides 2 sets of functions to be used interactively and for programming)    

@hadley Please share your thoughts here as well.

**Comment by dpastoor** [comment]
One other thing to consider @trinker is the saving two character arguments for interactive use is a little moot in the most recent version of Rstudio, at least with the library function. I don't know what wizardry the ide is using but if you type `library(dp` it will pick up that you have dplyr available, and then when you tab autocomplete it will also automatically add in quotes for library("dplyr")

The other thing I have found, again just food for thought, is that the way packrat picks up packages to archive (for now at least) is by explicitly searching for library() in R/rmd files, so even something like libraries <- c("lib1", "lib2") sapply(libraries, require/library, character.only=T) will not work. I wonder if that would also nix the compatibility with your pacman versions.  I see that you're targetting pacman for interactive use moreso (which is how I use it), but may come up in the future.

**Comment by khughitt** [comment]
:+1: It's never too late to learn good behavior.

If this package had been around for a long time, and there were many dependencies on this behavior, that might be one thing, but since you are relatively new, this seems like a good opportunity to adopt good practices.

**Comment by Dasonk** [comment]
Since we've released to cran already I don't think it would be good to break the current API.  Maybe we'll go the way of ggplot -> ggplot2 and make a pacman2 someday that breaks the current API and doesn't use non-standard evaluation.

But since we've released already I don't think we should change it. @trinker - thoughts? Should we close this?

**Comment by trinker** [comment]
Let's close for now
