### ISSUE TITLE
Drop devtools in favor of ghit

### ISSUE THREAD

**Issue by trinker** [trinker/pacman#92]
devtools is a lotta dependency.  ghit maybe all we need and lighterweight: https://cran.r-project.org/web/packages/ghit/ghit.pdf

Thoughts on using theis for `p_xxx_gh` functions over devtools?

**Comment by pat-s** [comment]
I recently tried `ghit` quite often for the same purpose and ended up with various installation errors in cases where `devtools` had no problems. I did not really inspect the problems in detail but maybe you should do some testing including packages from all kind of R fields (web, spatial, stats, Rcpp, shiny stuff, etc).

**Comment by Dasonk** [comment]
If we just wanted to make it lighter I think `remotes` would be an easier replacement since it's basically just the devtools github code without all the extras.

**Comment by trinker** [comment]
@Dasonk I do think makingit lighter would be good.  I see: https://cran.r-project.org/web/packages/gh/index.html now available too

**Comment by Dasonk** [comment]
gh looks like a more general/better version of https://github.com/Dasonk/githubSearch but I don't see installation.  I'd lean more toward using remotes since I don't really think we'd need to change anything.

**Comment by Dasonk** [comment]
Locations of devtools code:

- inst/build.R - I don't see an issue keeping devtools here (plus the alternatives don't provide the functionality needed).  But since it's a build script we don't need devtools in the DESCRIPTION to use it.
- inst/maintenance.R - Same issues as /inst/build.R 
- R/p_load_current_gh.R - devtools mentioned in documentation
- R/p_load_gh.R - devtools mentioned in documentation
- R/p_install_gh.R - We only use install_github here so we can replace with remotes::install_github
- R/utils.R - `devtools::github_pull` and `devtools::github_release` are used. We would need to either rewrite using code from other packages or take care of doing that stuff manually ourselves.  This is the major sticking point for using `devtools` right now.

So the issue isn't just changing to using `remotes::install_github` instead of `devtools::install_github` like I initially was thinking.  Thoughts on what to do about the uses in R/utils.R?

**Comment by trinker** [comment]
@Dasonk  **remotes** that you suggested has a `github_pull` that I assume is equivalent but not checked still leaves the `devtools::github_release`...It seems to be just a function to make:

```
structure(NA_integer_, class = "github_release")
```

not sure why a function is needed for this.  This is just surface level investigation

**Comment by Dasonk** [comment]
Sounds good. I'll play around with switching over to remotes and try to put a branch together to try it out. I'll take ownership of this issue unless you're already making code changes.

**Comment by trinker** [comment]
No please go ahead

**Comment by Dasonk** [comment]
Hmm.  I made the changes. It seems remotes is a bit harsher when it can't install. 

```
> p_load_gh("asdfasdf/asdfasdf") # when using devtools in the codebase
Warning message:
In p_load_gh("asdfasdf/asdfasdf") : 
Failed to install/load:
asdfasdf/asdfasdf
> load_all()  # after changing to use remotes
Loading pacman
> p_load_gh("asdfasdf/asdfasdf")
 Show Traceback
 
 Rerun with Debug
 Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/asdfasdf/asdfasdf/zipball/master'
```

We'll either need to do some additional error checking or just continue to use devtools.  I'll keep looking into it but I uncovered some other issues that I created issues for that we might want to investigate before tackling this particular problem.

**Comment by Dasonk** [comment]
I just wrapped the call to `remotes::install_github` in a `tryCatch` and that seemed to take care of it. I put the code in a new branch called 'remotes'.  Take a look at the diffs and play around with it.  I want to test it a bit more before merging it into master though.

**Comment by trinker** [comment]
nice and mostly this is to test slack integration
